//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterClassUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterClassUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] calculClassement {
            get {
                object obj = ResourceManager.GetObject("calculClassement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] converter {
            get {
                object obj = ResourceManager.GetObject("converter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;listEtudiants&quot;:{
        ///	&quot;filename&quot;: &quot;exemple\\listEtudiants.xlsx&quot;,
        ///	&quot;sheetname&quot;:&quot;Feuil1&quot;
        ///  },
        ///  
        ///  &quot;classement&quot;: {
        ///    &quot;filename&quot;: &quot;output_classement.xlsx&quot;,
        ///    &quot;sheetname&quot;: &quot;Sheet1&quot;
        ///  },
        ///  
        ///  &quot;ficheVoeux&quot;: [
        ///    {
        ///      &quot;filename&quot;: &quot;exemple\\fdv acad.xlsx&quot;,
        ///      &quot;sheetname&quot;: &quot;Feuil1&quot;
        ///    }
        ///  ],
        ///  
        ///  &quot;choixStartIndex&quot;: 3,
        ///  
        ///  &quot;formule&quot; :{
        ///		&quot;form&quot;:&quot;(($1$+$2$+$3$+$4$+$5$+$6$)/6)*(1-$7$*($8$+$9$/2+$10$/4))&quot;,
        ///		&quot;1&quot;:&quot;S1&quot;, 
        ///		&quot;2&quot;:&quot;S2&quot;,
        ///		&quot;3&quot;:&quot;S3&quot;,	
        ///		&quot;4&quot;:&quot;S4&quot;, 
        ///		&quot;5&quot;:&quot;S5&quot;,
        ///		&quot;6&quot;:&quot;S6&quot;, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string default_config {
            get {
                return ResourceManager.GetString("default_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_info_30 {
            get {
                object obj = ResourceManager.GetObject("icons8-info-30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_macos_close_30 {
            get {
                object obj = ResourceManager.GetObject("icons8-macos-close-30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_macos_minimize_30__1_ {
            get {
                object obj = ResourceManager.GetObject("icons8-macos-minimize-30 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_microsoft_excel_30 {
            get {
                object obj = ResourceManager.GetObject("icons8-microsoft-excel-30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_numbered_list_30 {
            get {
                object obj = ResourceManager.GetObject("icons8-numbered-list-30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_services_30 {
            get {
                object obj = ResourceManager.GetObject("icons8-services-30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] input {
            get {
                object obj = ResourceManager.GetObject("input", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] process_classement {
            get {
                object obj = ResourceManager.GetObject("process_classement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] process_oriontation {
            get {
                object obj = ResourceManager.GetObject("process_oriontation", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
